"""change business id to autoincrement and remove help_request business_id

Revision ID: 12801ce5feae
Revises: 576fbd486ce5
Create Date: 2025-11-16 10:14:50.910618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12801ce5feae'
down_revision: Union[str, None] = '576fbd486ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kb_article', 'business_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('kb_article_business_id_fkey', 'kb_article', type_='foreignkey')
    op.create_foreign_key(None, 'kb_article', 'business', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kb_article', type_='foreignkey')
    op.create_foreign_key('kb_article_business_id_fkey', 'kb_article', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('kb_article', 'business_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.add_column('help_request', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('help_request_business_id_fkey', 'help_request', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('business', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
